language: ruby
cache: bundler
sudo: false

script: "bundle exec rspec spec"

rvm:
  - 2.2.1
before_install: gem install bundler -v 1.10.6

addons:
  code_climate:
    repo_token: 5672a73877da19545a001fd9
